-- MYUSER 계정에 BOOK 테이블 생성
CREATE TABLE book (
    num        NUMBER NOT NULL,
    title      VARCHAR2(200 BYTE) NOT NULL,
    author     VARCHAR2(40 BYTE),
    publisher  VARCHAR2(40 BYTE),
    book_date  VARCHAR2(20 BYTE),
    isbn       VARCHAR2(20 BYTE),
    CONSTRAINT book_pk PRIMARY KEY ( num )
        USING INDEX (
            CREATE UNIQUE INDEX book_pk ON
                book (
                    num
                ASC )
                    LOGGING TABLESPACE system PCTFREE 10 INITRANS 2
                        STORAGE ( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS UNLIMITED FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL
                        DEFAULT )
                        NOPARALLEL
        )
    ENABLE
)
LOGGING TABLESPACE system PCTFREE 10 PCTUSED 40 INITRANS 1
    STORAGE ( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS UNLIMITED FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT )
    NOPARALLEL;
    
-- SEQ_BOOK 시퀀스도 생성
CREATE SEQUENCE seq_book INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 NOCACHE ORDER;